### PR TITLE
Bug fixes and some changes on the way ui works

### PR DESCRIPTION
**Pull request by EuniceChen1**
Fixed bugs on the gear menu widget that only calls for the search option box. 

Fixed update versionless checkbox. Seems to be working fine for me right now. 

Instead of all ui's showing right at the beginning, which can seem intimidating for new users, I closed drop plate dock and description dock upon start up. This is to make the app less intimidating and confusing for new users who are not technical. The docks can be reopened through the gear menu widget that has been fixed. 

Fixed the way maya launches on standalone app. The current way it launches if just like double-clicking on the maya file itself. This does not work if there are multiple versions of maya installed on the same computer. os.startfile will only recognised the most recent installed version. Made changes so that upon clicking open snapshot, it will look for the specific maya version and open that. (Maya path is coded in as the default path on "C:/Program Files/Autodesk")

### CODE REVIEW

**Review by listyque — CHANGES_REQUESTED** [review]
I would check the global env first "MAYA_LOCATION", and then if it is empty use abs path to maya dir. But it is questionable, and should be added to configs.

**Review by listyque — COMMENTED** [review]
But how users will know there is description dock and drop plate exists? :0

**Review by listyque — APPROVED** [review]
Fixed.

**Review by listyque — APPROVED** [review]
Thanks

**Comment by EuniceChen1** [comment]
For how users will know if there is description dock and drop plate dock, just like how users won't know what's inside the Menu button until they click into it. It's like anyone, using a new app where they will be discovering certain things on their own, but the initial landing page should be easy to understand at one glance. This is my opinion.

Thanks.

**Review by listyque — CHANGES_REQUESTED** [review]
There should be checking if there is metadata present.

**Comment by EuniceChen1** [comment]
When I changed the ui creation to not show description dock and drop plate dock on start up, it only applied to the first tab. So this code change is so that this change applies to all tabs

**Comment by EuniceChen1** [comment]
Yes.  I basically just automated that for when it launches. But if the user want to change the look again after launch for all the tabs, they still can use File > Current View To All Tabs.

**Comment by listyque** [comment]
I agree with you. But.
I added checkbox to settings, so users will be able to use your enhancement if they wanted.
Checkbox needed because not every tabs should be equal every time i run, for example, Textures tab should have Snapshot browser, but when i have tab without snapshots at all i will make the layout different.
Basically users should have choice if they want.
This will be in next "frequent" commit.

**Comment by EuniceChen1** [comment]
Sure, that's good with me. Thanks!

**Pull request merged**
